CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');


-- Table structure for table `classification`
CREATE TABLE public.classification(
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)	
);

INSERT INTO public.classification (classification_name)
	VALUES
		('Custom'),
		('Sport'),
		('SUV'),
		('Truck'),
		('Sedan');

-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory
(
  	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  	inv_make character varying NOT NUll,
	inv_model character varying NOT NULL,
	inv_year character(4) NOT NULL,
	inv_description text NOT NULL,
	inv_image character varying NOT NULL,
	inv_thumbnail character varying NOT NULL,
	inv_price numeric(9, 0) NOT NULL,
	inv_miles integer NOT NULL,
	inv_color character varying NOT NULL,
	classification_id integer NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY(inv_id)
);

-- Data for table `inventory`

INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
  )
VALUES   (
    'Chevy',
    'Camaro',
    '2018',
    'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
    '/images/camaro.jpg',
    '/images/camaro-tn.jpg',
    25000,
    101222,
    'Silver',
    2
  ), (
    'Batmobile',
    'Custom',
    '2007',
    'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during rush hour.',
    '/images/batmobile.jpg',
    '/images/batmobile-tn.jpg',
    65000,
    29887,
    'Black',
    1
  ), (
    'FBI',
    'Surveillance Van',
    '2016',
    'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.',
    '/images/survan.jpg',
    '/images/survan-tn.jpg',
    20000,
    19851,
    'Brown',
    1
  ), (
    'Dog ',
    'Car',
    '1997',
    'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.',
    '/images/dog-car.jpg',
    '/images/dog-car-tn.jpg',
    35000,
    71632,
    'White',
    1
  ), (
    'Jeep',
    'Wrangler',
    '2019',
    'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!',
    '/images/wrangler.jpg',
    '/images/wrangler-tn.jpg',
    28045,
    41205,
    'Yellow',
    3
  ), (
    'Lamborghini',
    'Adventador',
    '2016',
    'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
    '/images/adventador.jpg',
    '/images/adventador-tn.jpg',
    417650,
    71003,
    'Blue',
    2
  ), (
    'Aerocar International',
    'Aerocar',
    '1963',
    'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!',
    '/images/aerocar.jpg',
    '/images/aerocar-tn.jpg',
    700000,
    18956,
    'Red',
    1
  ), (
    'Monster',
    'Truck',
    '1995',
    'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.',
    '/images/monster-truck.jpg',
    '/images/monster-truck-tn.jpg',
    150000,
    3998,
    'purple',
    1
  ), (
    'Cadillac',
    'Escalade',
    '2019',
    'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
    '/images/escalade.jpg',
    '/images/escalade-tn.jpg',
    75195,
    41958,
    'Black',
    4
  ), (
    'GM',
    'Hummer',
    '2016',
    'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
    '/images/hummer.jpg',
    '/images/hummer-tn.jpg',
    58800,
    56564,
    'Yellow',
    4
  ), (
    'Mechanic',
    'Special',
    '1964',
    'Not sure where this car came from. however with a little tlc it will run as good a new.',
    '/images/mechanic.jpg',
    '/images/mechanic-tn.jpg',
    100,
    200125,
    'Rust',
    5
  ), (
    'Ford',
    'Model T',
    '1921',
    'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
    '/images/model-t.jpg',
    '/images/model-t-tn.jpg',
    30000,
    26357,
    'Black',
    5
  ), (
    'Mystery',
    'Machine',
    '1999',
    'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.',
    '/images/mystery-van.jpg',
    '/images/mystery-van-tn.jpg',
    10000,
    128564,
    'Green',
    1
  ),
  (
    'Spartan',
    'Fire Truck',
    '2012',
    'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.',
    '/images/fire-truck.jpg',
    '/images/fire-truck-tn.jpg',
    50000,
    38522,
    'Red',
    4
  ), (
    'Ford',
    'Crown Victoria',
    '2013',
    'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.',
    '/images/crwn-vic.jpg',
    '/images/crwn-vic-tn.jpg',
    10000,
    108247,
    'White',
    5
  );


-- Create a relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification(classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);


-- String replace in the description field.
UPDATE public.inventory
	SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM';

-- String replacement in more than one field in a single query.
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, 's/', 's/vehicles/'), 
	inv_thumbnail= REPLACE(inv_thumbnail, 's/', 's/vehicles/');


--************** PERSONAL PROJECT *****************--

-- Table structure for table `category`
CREATE TABLE public.category(
    category_id INT GENERATED BY DEFAULT AS IDENTITY,
    category_name CHARACTER VARYING NOT NULL,
    CONSTRAINT category_pk PRIMARY KEY (category_id)
);

INSERT INTO public.category (category_name)
	VALUES
		('Electronics'),
    ('Pets'),
    ('Fruits');

-- Table structure for table `type`
CREATE TABLE public.type(
    type_id INT GENERATED BY DEFAULT AS IDENTITY,
    type_name CHARACTER VARYING NOT NULL,
    type_image CHARACTER VARYING NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT type_pk PRIMARY KEY (type_id),
    CONSTRAINT fk_category FOREIGN KEY (category_id)
        REFERENCES public.category (category_id)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

INSERT INTO public.type (type_name, type_image, category_id)
	VALUES
		('Phones', '/images/types/phones.jpg', 1),
    ('PC', '/images/types/pc.jpg', 1),
    ('Birds', '/images/types/birds.jpg', 2),
    ('Avocados', '/images/types/avocados.jpg', 3),
    ('Bananas', '/images/types/bananas.jpg', 3),
    ('Dogs', '/images/types/dogs.jpg', 2),
    ('Cats', '/images/types/cats.jpg', 2),
    ('Apples', '/images/types/apples.jpg', 3);

-- Table structure for table `product`
CREATE TABLE IF NOT EXISTS public.product
(
    product_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_name CHARACTER VARYING NOT NULL,
    product_description TEXT,
    product_image CHARACTER VARYING NOT NULL,
    product_price NUMERIC(9, 2) NOT NULL,
    type_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (product_id),
    CONSTRAINT fk_product_type FOREIGN KEY (type_id)
        REFERENCES public.type (type_id)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES public.category (category_id)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

INSERT INTO public.product (product_name, product_description, product_image, product_price, type_id, category_id)
VALUES
    ('Apple 1', '', '/images/products/apple1.jpg', '15.00', 8, 3),
    ('Apple 2', '', '/images/products/apple2.jpg', '13.35', 8, 3),
    ('Apple 3', '', '/images/products/apple3.jpg', '1021.00', 8, 3),
    ('Avocado 1', '', '/images/products/avocado1.jpg', '7.77', 4, 3),
    ('Avocado 2', '', '/images/products/avocado2.jpg', '9.31', 4, 3),
    ('Banana 1', '', '/images/products/banana1.jpg', '11.01', 5, 3),
    ('Banana 2', '', '/images/products/banana2.jpg', '20.55', 5, 3),
    ('Banana 3', '', '/images/products/banana3.jpg', '18.65', 5, 3),
    ('Bird 1', '', '/images/products/bird1.jpg', '800.35', 3, 2),
    ('Bird 2', '', '/images/products/bird2.jpg', '650.35', 3, 2),
    ('Bird 3', '', '/images/products/bird3.jpg', '670.35', 3, 2),
    ('SAMSUNG', '', '/images/products/samsung.jpg', '500.35', 1, 1),
    ('Iphone 15', '', '/images/products/iphone.jpg', '999.99', 1, 1),
    ('Cat 1', '', '/images/products/katty1.jpg', '250.03', 7, 2),
    ('Cat 2', '', '/images/products/katty2.jpg', '235.88', 7, 2),
    ('Cat 3', '', '/images/products/katty3.jpg', '222.21', 7, 2),
    ('Cat 4', '', '/images/products/katty4.jpg', '250.35', 7, 2),
    ('Dog 1', '', '/images/products/doggy1.jpg', '500.35', 6, 2),
    ('Dog 2', '', '/images/products/doggy2.jpg', '450.35', 6, 2),
    ('Dog 3', '', '/images/products/doggy3.jpg', '480.35', 6, 2),
    ('Dog 4', '', '/images/products/doggy4.jpg', '399.99', 6, 2),
    ('Dog 5', '', '/images/products/doggy5.jpg', '250.35', 6, 2),
    ('TOSHIBA', '', '/images/products/toshiba.jpg', '777.99', 2, 1),
    ('Dell', '', '/images/products/dell.jpg', '600.99', 2, 1),
    ('HP', '', '/images/products/hp.jpg', '599.99', 2, 1);



